---
abstract: 'XMPP/Jabber protocol API'
author:
  - 'Tom Molesworth <protocol-xmpp@entitymodel.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200004, CPAN::Meta::Converter version 2.110440'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Protocol-XMPP
requires:
  Authen::SASL: 0
  MIME::Base64: 0
  XML::LibXML::SAX::ChunkParser: 0.00003
  parent: 0
version: 0.004
